namespace Flagrum.Core.Physics.Collision;

public enum PhysicsShapeType
{
    SHAPE_TYPE_NULL = 0x0,
    SHAPE_TYPE_SPHERE = 0x1,
    SHAPE_TYPE_BOX = 0x2,
    SHAPE_TYPE_CAPSULE = 0x3,
    SHAPE_TYPE_CYLINDER = 0x4,
    SHAPE_TYPE_ELLIPSE = 0x5,
    SHAPE_TYPE_HEMISPHERE = 0x6,
    SHAPE_TYPE_PLANE = 0x7,
    SHAPE_TYPE_LOCKPLANE = 0x8,
    SHAPE_TYPE_CONVEX = 0x9,
    SHAPE_TYPE_TRIANGLE_MESH = 0xA,
    SHAPE_TYPE_STRETCH_CAPSULE = 0xB,
    SHAPE_TYPE_THREE_POINT_PLANE = 0xC,
    SHAPE_TYPE_CONE = 0xD,
    SHAPE_TYPE_ID_MESH = 0xE,
    SHAPE_TYPE_CONSTRAINT_FIXED = 0xF,
    SHAPE_TYPE_CONSTRAINT_DISTANCE = 0x10,
    SHAPE_TYPE_CONSTRAINT_SPHERICAL = 0x11,
    SHAPE_TYPE_CONSTRAINT_REVOLUTE = 0x12,
    SHAPE_TYPE_CONSTRAINT_PRISMATIC = 0x13
}