# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Flagrum
open_collective: # Replace with a single Open Collective username
ko_fi: kizari
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://www.paypal.com/donate/?business=GMWBY6FGMMCCA&no_recurring=0&item_name=Creating+next+generation+modding+tools+for+Final+Fantasy+XV+and+providing+comprehensive+guides+for+users+of+all+skill+levels.&currency_code=NZD', 'https://www.buymeacoffee.com/Exineris']
