//----------------------
// <auto-generated>
// This file was automatically generated. Any changes to it will be lost if and when the file is regenerated.
// </auto-generated>
//----------------------
#pragma warning disable

using System;
using SQEX.Luminous.Core.Object;
using System.Collections.Generic;
using CodeDom = System.CodeDom;
using UnityEngine;

namespace SQEX.Ebony.Framework.Entity
{
    public partial class TransformEntity : SQEX.Ebony.Framework.Entity.Entity
    {
        public override void SetupGameObject(object gameObject)
        {
            base.SetupGameObject(gameObject);
            //gameObject.transform.position = this.position_;
        }

    }
}