# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/unittest_mset.proto
"""Generated protocol buffer code."""
from ...google.protobuf import descriptor as _descriptor
from ...google.protobuf import descriptor_pool as _descriptor_pool
from ...google.protobuf import symbol_database as _symbol_database
from ...google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from ...google.protobuf import \
    unittest_mset_wire_format_pb2 as google_dot_protobuf_dot_unittest__mset__wire__format__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#google/protobuf/unittest_mset.proto\x12\x11protobuf_unittest\x1a/google/protobuf/unittest_mset_wire_format.proto\"Z\n\x17TestMessageSetContainer\x12?\n\x0bmessage_set\x18\x01 \x01(\x0b\x32*.proto2_wireformat_unittest.TestMessageSet\"\x9f\x01\n\x1dNestedTestMessageSetContainer\x12=\n\tcontainer\x18\x01 \x01(\x0b\x32*.protobuf_unittest.TestMessageSetContainer\x12?\n\x05\x63hild\x18\x02 \x01(\x0b\x32\x30.protobuf_unittest.NestedTestMessageSetContainer\"\xf9\x01\n\x18TestMessageSetExtension1\x12\t\n\x01i\x18\x0f \x01(\x05\x12=\n\trecursive\x18\x10 \x01(\x0b\x32*.proto2_wireformat_unittest.TestMessageSet\x12\x19\n\rtest_aliasing\x18\x11 \x01(\tB\x02\x08\x02\x32x\n\x15message_set_extension\x12*.proto2_wireformat_unittest.TestMessageSet\x18\xb0\xa6^ \x01(\x0b\x32+.protobuf_unittest.TestMessageSetExtension1\"\xa1\x01\n\x18TestMessageSetExtension2\x12\x0b\n\x03str\x18\x19 \x01(\t2x\n\x15message_set_extension\x12*.proto2_wireformat_unittest.TestMessageSet\x18\xf9\xbb^ \x01(\x0b\x32+.protobuf_unittest.TestMessageSetExtension2\"K\n\rNestedTestInt\x12\t\n\x01\x61\x18\x01 \x01(\x07\x12/\n\x05\x63hild\x18\x02 \x01(\x0b\x32 .protobuf_unittest.NestedTestInt\"\xc4\x01\n\x18TestMessageSetExtension3\x12-\n\x03msg\x18# \x01(\x0b\x32 .protobuf_unittest.NestedTestInt2y\n\x15message_set_extension\x12*.proto2_wireformat_unittest.TestMessageSet\x18\xa9\xc3\x8e] \x01(\x0b\x32+.protobuf_unittest.TestMessageSetExtension3\"n\n\rRawMessageSet\x12\x33\n\x04item\x18\x01 \x03(\n2%.protobuf_unittest.RawMessageSet.Item\x1a(\n\x04Item\x12\x0f\n\x07type_id\x18\x02 \x02(\x05\x12\x0f\n\x07message\x18\x03 \x02(\x0c\x42\x05H\x01\xf8\x01\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.protobuf.unittest_mset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    google_dot_protobuf_dot_unittest__mset__wire__format__pb2.TestMessageSet.RegisterExtension(
        _TESTMESSAGESETEXTENSION1.extensions_by_name['message_set_extension'])
    google_dot_protobuf_dot_unittest__mset__wire__format__pb2.TestMessageSet.RegisterExtension(
        _TESTMESSAGESETEXTENSION2.extensions_by_name['message_set_extension'])
    google_dot_protobuf_dot_unittest__mset__wire__format__pb2.TestMessageSet.RegisterExtension(
        _TESTMESSAGESETEXTENSION3.extensions_by_name['message_set_extension'])

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'H\001\370\001\001'
    _TESTMESSAGESETEXTENSION1.fields_by_name['test_aliasing']._options = None
    _TESTMESSAGESETEXTENSION1.fields_by_name['test_aliasing']._serialized_options = b'\010\002'
    _TESTMESSAGESETCONTAINER._serialized_start = 107
    _TESTMESSAGESETCONTAINER._serialized_end = 197
    _NESTEDTESTMESSAGESETCONTAINER._serialized_start = 200
    _NESTEDTESTMESSAGESETCONTAINER._serialized_end = 359
    _TESTMESSAGESETEXTENSION1._serialized_start = 362
    _TESTMESSAGESETEXTENSION1._serialized_end = 611
    _TESTMESSAGESETEXTENSION2._serialized_start = 614
    _TESTMESSAGESETEXTENSION2._serialized_end = 775
    _NESTEDTESTINT._serialized_start = 777
    _NESTEDTESTINT._serialized_end = 852
    _TESTMESSAGESETEXTENSION3._serialized_start = 855
    _TESTMESSAGESETEXTENSION3._serialized_end = 1051
    _RAWMESSAGESET._serialized_start = 1053
    _RAWMESSAGESET._serialized_end = 1163
    _RAWMESSAGESET_ITEM._serialized_start = 1123
    _RAWMESSAGESET_ITEM._serialized_end = 1163
# @@protoc_insertion_point(module_scope)
