name: Bug Report
description: Report a Flagrum bug.
title: '[Bug]: '
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Do **not** report issues with individual mods. Direct those to the author of the mod.

        Please fill this form out in its entirety and with as much detail as possible. We cannot help you without the necessary information to do so.
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you running Flagrum on?
      options:
        - Windows 10 64-Bit
        - Windows 11 64-Bit
        - Other
    validations:
      required: true
  - type: dropdown
    id: game-version
    attributes:
      label: Game Version
      description: Which version of the game are you applying your mods to?
      options:
        - Latest Steam Release
        - Other Game Store (please specify in "Additional context")
        - Debug Executable
        - Avatara Executable
        - Other (please specify in "Additional context")
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Flagrum are you running? (You can find this in the bottom-left corner of the Flagrum window).
      placeholder: e.g. 1.5.0
    validations:
      required: true
  - type: textarea
    id: bug
    attributes:
      label: Description of the bug
      description: Explain in as much detail as possible what went wrong, and what you expected to happen instead.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce the bug
      description: A numbered list of the steps to take to trigger the bug.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: crash-logs
    attributes:
      label: Crash logs
      description: |
        If Flagrum crashed, please attach **all** crash logs in the `%LOCALAPPDATA%\Flagrum\crashes` folder with the timestamp matching the date/time of the crash.

        You can attach log files by clicking this area to highlight it and then drag the files and drop them on it.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.

        You can attach images by clicking this area to highlight it and then drag the files and drop them on it.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other information or context here that may help with figuring out what went wrong.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree that you have done your due diligence before asking for someone to give up their free time to help you.

        **Failure to comply with these terms may result in a ban from this repository.**
      options:
        - label: I confirm that this bug report is pertaining to Flagrum, **not** an individual mod, the game itself, or an issue with my system or files.
          required: true
        - label: I confirm that I am using a legitimate copy of the game.
          required: true
        - label: I confirm that I installed Flagrum with a clean installation of the game, and have not used any tools other than Flagrum to mod my game files.
          required: true
        - label: If my issue relates to the game itself crashing or exhibiting unexpected behaviour, I confirm that I have tried running a clean **unmodded** installation of the game to see if this resolves my issue before filing a bug report.
          required: true
