# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/internal/packed_field_test.proto
"""Generated protocol buffer code."""
from ....google.protobuf import descriptor as _descriptor
from ....google.protobuf import descriptor_pool as _descriptor_pool
from ....google.protobuf import symbol_database as _symbol_database
from ....google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n0google/protobuf/internal/packed_field_test.proto\x12\x1fgoogle.protobuf.python.internal\"\xdb\x03\n\x0fTestPackedTypes\x12\x16\n\x0erepeated_int32\x18\x01 \x03(\x05\x12\x16\n\x0erepeated_int64\x18\x02 \x03(\x03\x12\x17\n\x0frepeated_uint32\x18\x03 \x03(\r\x12\x17\n\x0frepeated_uint64\x18\x04 \x03(\x04\x12\x17\n\x0frepeated_sint32\x18\x05 \x03(\x11\x12\x17\n\x0frepeated_sint64\x18\x06 \x03(\x12\x12\x18\n\x10repeated_fixed32\x18\x07 \x03(\x07\x12\x18\n\x10repeated_fixed64\x18\x08 \x03(\x06\x12\x19\n\x11repeated_sfixed32\x18\t \x03(\x0f\x12\x19\n\x11repeated_sfixed64\x18\n \x03(\x10\x12\x16\n\x0erepeated_float\x18\x0b \x03(\x02\x12\x17\n\x0frepeated_double\x18\x0c \x03(\x01\x12\x15\n\rrepeated_bool\x18\r \x03(\x08\x12Y\n\x14repeated_nested_enum\x18\x0e \x03(\x0e\x32;.google.protobuf.python.internal.TestPackedTypes.NestedEnum\"\'\n\nNestedEnum\x12\x07\n\x03\x46OO\x10\x00\x12\x07\n\x03\x42\x41R\x10\x01\x12\x07\n\x03\x42\x41Z\x10\x02\"\xec\x03\n\x11TestUnpackedTypes\x12\x1a\n\x0erepeated_int32\x18\x01 \x03(\x05\x42\x02\x10\x00\x12\x1a\n\x0erepeated_int64\x18\x02 \x03(\x03\x42\x02\x10\x00\x12\x1b\n\x0frepeated_uint32\x18\x03 \x03(\rB\x02\x10\x00\x12\x1b\n\x0frepeated_uint64\x18\x04 \x03(\x04\x42\x02\x10\x00\x12\x1b\n\x0frepeated_sint32\x18\x05 \x03(\x11\x42\x02\x10\x00\x12\x1b\n\x0frepeated_sint64\x18\x06 \x03(\x12\x42\x02\x10\x00\x12\x1c\n\x10repeated_fixed32\x18\x07 \x03(\x07\x42\x02\x10\x00\x12\x1c\n\x10repeated_fixed64\x18\x08 \x03(\x06\x42\x02\x10\x00\x12\x1d\n\x11repeated_sfixed32\x18\t \x03(\x0f\x42\x02\x10\x00\x12\x1d\n\x11repeated_sfixed64\x18\n \x03(\x10\x42\x02\x10\x00\x12\x1a\n\x0erepeated_float\x18\x0b \x03(\x02\x42\x02\x10\x00\x12\x1b\n\x0frepeated_double\x18\x0c \x03(\x01\x42\x02\x10\x00\x12\x19\n\rrepeated_bool\x18\r \x03(\x08\x42\x02\x10\x00\x12]\n\x14repeated_nested_enum\x18\x0e \x03(\x0e\x32;.google.protobuf.python.internal.TestPackedTypes.NestedEnumB\x02\x10\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.protobuf.internal.packed_field_test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_int32']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_int32']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_int64']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_int64']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_uint32']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_uint32']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_uint64']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_uint64']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_sint32']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_sint32']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_sint64']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_sint64']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_fixed32']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_fixed32']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_fixed64']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_fixed64']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_sfixed32']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_sfixed32']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_sfixed64']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_sfixed64']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_float']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_float']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_double']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_double']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_bool']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_bool']._serialized_options = b'\020\000'
    _TESTUNPACKEDTYPES.fields_by_name['repeated_nested_enum']._options = None
    _TESTUNPACKEDTYPES.fields_by_name['repeated_nested_enum']._serialized_options = b'\020\000'
    _TESTPACKEDTYPES._serialized_start = 86
    _TESTPACKEDTYPES._serialized_end = 561
    _TESTPACKEDTYPES_NESTEDENUM._serialized_start = 522
    _TESTPACKEDTYPES_NESTEDENUM._serialized_end = 561
    _TESTUNPACKEDTYPES._serialized_start = 564
    _TESTUNPACKEDTYPES._serialized_end = 1056
# @@protoc_insertion_point(module_scope)
