<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationIcon>Resources\flagrum.ico</ApplicationIcon>
        <DebugType>embedded</DebugType>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AvaloniaVersion>11.3.5</AvaloniaVersion>
        <BaseVersion>1.6.5</BaseVersion> <!-- Current version of the application -->
        <Version>$(BaseVersion)</Version> <!-- Semantic version to show on GitHub -->
        <AssemblyVersion>$(BaseVersion)</AssemblyVersion> <!-- Version of the assembly for internal purposes -->
        <FileVersion>$(BaseVersion)</FileVersion> <!-- Version that is displayed in Windows for the application -->
        <SolutionDir>$([System.IO.Path]::GetDirectoryName($(MSBuildProjectDirectory)))</SolutionDir>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**\*.*"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="FontAwesome5" Version="2.1.6"/>
        <!--        <PackageReference Include="HotAvalonia" Version="3.0.0" PrivateAssets="All" Publish="True"/>-->
        <PackageReference Include="MessageBox.Avalonia" Version="3.2.0"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="6.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="9.0.8"/>
        <PackageReference Include="Velopack" Version="0.0.320"/>
        <PackageReference Include="Drautos" Version="1.0.0"/>
        <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.0.3"/>
    </ItemGroup>

    <!-- Will include the Premium library only in CI builds. The GitHub workflow handles adding this package source. -->
    <ItemGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <PackageReference Include="Flagrum.Premium" Version="1.0.4"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\tools\Flagrum.Generators\Flagrum.Generators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\Flagrum.Application\Flagrum.Application.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="steam_appid.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="steam_api64.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <Content Include="Resources\preview.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Resources\default.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Resources\Textures\teal.btex">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\fonts\MaterialIcons-Regular.ttf">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\fonts\MaterialIconsOutlined-Regular.otf">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\fonts\Play-Regular.ttf">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\fonts\Roboto-Regular.ttf">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\app.css">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\index.html">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\interop.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Remove="Resources\earc.png"/>
        <Content Include="Resources\earc.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Remove="Resources\Play-Regular.ttf"/>
        <Resource Include="Assets\logo_outlined.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Resource>
        <None Update="libnvtt.so">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Assets\patreon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Resource>
        <Resource Include="Assets\Play-Regular.ttf">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Resource>
        <None Remove="Resources\logo.png"/>
        <Resource Include="Resources\logo.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Resource>
        <None Remove="Resources\logo_outlined.png"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\Localisation.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Localisation.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\Localisation.ja-JP.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Localisation.ja-JP.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\Localisation.zh-cn.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Localisation.zh-cn.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\Localisation.zh-hk.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Localisation.zh-hk.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Resources\Localisation.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Localisation.resx</DependentUpon>
        </Compile>
        <Compile Update="Resources\Localisation.ja-JP.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Localisation.ja-JP.resx</DependentUpon>
        </Compile>
        <Compile Update="Resources\Localisation.zh-cn.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Localisation.zh-cn.resx</DependentUpon>
        </Compile>
        <Compile Update="Resources\Localisation.zh-hk.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Localisation.zh-hk.resx</DependentUpon>
        </Compile>
        <Compile Update="ApplicationHost\App.axaml.cs">
            <DependentUpon>App.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="ApplicationHost\MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="ApplicationHost\SplashWindow.axaml.cs">
            <DependentUpon>SplashWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="ApplicationHost\Shell\CustomShellWindow.axaml"/>
        <AdditionalFiles Include="ApplicationHost\Shell\PlasmaShellButton.axaml"/>
    </ItemGroup>

</Project>
