namespace Flagrum.Core.Graphics.Models;

public enum PrimitiveType
{
    PrimitiveTypePointList = 0x0,
    PrimitiveTypeLineList = 0x1,
    PrimitiveTypeLineStrip = 0x2,
    PrimitiveTypeTriangleList = 0x3,
    PrimitiveTypeTriangleStrip = 0x4,
    PrimitiveTypeLineListADJ = 0x5,
    PrimitiveTypeLineStripADJ = 0x6,
    PrimitiveTypeTriangleListADJ = 0x7,
    PrimitiveTypeTriangleStripADJ = 0x8,
    PrimitiveType1_ControlPointPatchList = 0x9,
    PrimitiveType2_ControlPointPatchList = 0xA,
    PrimitiveType3_ControlPointPatchList = 0xB,
    PrimitiveType4_ControlPointPatchList = 0xC,
    PrimitiveType5_ControlPointPatchList = 0xD,
    PrimitiveType6_ControlPointPatchList = 0xE,
    PrimitiveType7_ControlPointPatchList = 0xF,
    PrimitiveType8_ControlPointPatchList = 0x10,
    PrimitiveType9_ControlPointPatchList = 0x11,
    PrimitiveType10_ControlPointPatchList = 0x12,
    PrimitiveType11_ControlPointPatchList = 0x13,
    PrimitiveType12_ControlPointPatchList = 0x14,
    PrimitiveType13_ControlPointPatchList = 0x15,
    PrimitiveType14_ControlPointPatchList = 0x16,
    PrimitiveType15_ControlPointPatchList = 0x17,
    PrimitiveType16_ControlPointPatchList = 0x18,
    PrimitiveType17_ControlPointPatchList = 0x19,
    PrimitiveType18_ControlPointPatchList = 0x1A,
    PrimitiveType19_ControlPointPatchList = 0x1B,
    PrimitiveType20_ControlPointPatchList = 0x1C,
    PrimitiveType21_ControlPointPatchList = 0x1D,
    PrimitiveType22_ControlPointPatchList = 0x1E,
    PrimitiveType23_ControlPointPatchList = 0x1F,
    PrimitiveType24_ControlPointPatchList = 0x20,
    PrimitiveType25_ControlPointPatchList = 0x21,
    PrimitiveType26_ControlPointPatchList = 0x22,
    PrimitiveType27_ControlPointPatchList = 0x23,
    PrimitiveType28_ControlPointPatchList = 0x24,
    PrimitiveType29_ControlPointPatchList = 0x25,
    PrimitiveType30_ControlPointPatchList = 0x26,
    PrimitiveType31_ControlPointPatchList = 0x27,
    PrimitiveType32_ControlPointPatchList = 0x28,
    PrimitiveTypeNum = 0x29
}