# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/internal/import_test_package/import_public_nested.proto
"""Generated protocol buffer code."""
from ....google.protobuf import descriptor as _descriptor
from ....google.protobuf import descriptor_pool as _descriptor_pool
from ....google.protobuf import symbol_database as _symbol_database
from ....google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\nGgoogle/protobuf/internal/import_test_package/import_public_nested.proto\x12\x33google.protobuf.python.internal.import_test_package\".\n\x19ImportPublicNestedMessage\x12\x11\n\x05value\x18\x01 \x01(\x05:\x02\x35\x38')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR,
                                        'google.protobuf.internal.import_test_package.import_public_nested_pb2',
                                        globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _IMPORTPUBLICNESTEDMESSAGE._serialized_start = 128
    _IMPORTPUBLICNESTEDMESSAGE._serialized_end = 174
# @@protoc_insertion_point(module_scope)
