<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <DebugType>embedded</DebugType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Blazored.TextEditor" Version="1.0.8"/>
        <PackageReference Include="CsvHelper" Version="30.0.1"/>
        <PackageReference Include="Injectio" Version="3.3.0"/>
        <PackageReference Include="MarkdownSharp" Version="2.0.5"/>
        <PackageReference Include="MessagePack" Version="2.5.124"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.*" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.9"/>
        <PackageReference Include="Microsoft.Extensions.Localization" Version="6.0.7"/>
        <PackageReference Include="Quickenshtein" Version="1.5.1"/>
        <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.4"/>
        <PackageReference Include="System.Net.Http.Json" Version="6.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Flagrum.Components\Flagrum.Components.csproj"/>
        <ProjectReference Include="..\Flagrum.Core\Flagrum.Core.csproj"/>
        <ProjectReference Include="..\..\tools\Flagrum.Generators\Flagrum.Generators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Steamworks.NET">
            <HintPath>..\..\libs\Steamworks.NET.dll</HintPath>
        </Reference>
        <Reference Include="System.Drawing.Common"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Features\Information\Markup\About.html">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
